### ISSUE TITLE
Topic: Darželiai

### ISSUE THREAD

**Issue by kestutisv** [sirex/manopozicija.lt#8]

**Comment by kestutisv** [comment]
DĖL VAIKŲ PRIĖMIMO Į VILNIAUS MIESTO ŠVIETIMO ĮSTAIGŲ IKIMOKYKLINIO IR PRIEŠMOKYKLINIO UGDYMO GRUPES ORGANIZAVIMO TVARKOS APRAŠO TVIRTINIMO http://www.vilnius.lt/lit/Del_vaiku_priemimo_i_vilniaus_miesto_svi/8/40359513/10145954

**Comment by kestutisv** [comment]
Išbraukta iš darbotvarkės DĖL MĖNESINIO MOKESČIO KOMPENSAVIMO UŽ IKIMOKYKLINIO IR PRIEŠMOKYKLINIO AMŽIAUS VAIKŲ IŠLAIKYMĄ IR PRIEŽIŪRĄ VILNIAUS MIESTO NEVALSTYBINĖSE ŠVIETIMO ĮSTAIGOSE, VYKDANČIOSE IKIMOKYKLINIO IR PRIEŠMOKYKLINIO UGDYMO PROGRAMAS, TVARKOS APRAŠO PATVIRTINIMO http://www.vilnius.lt/lit/Del_menesinio_mokescio_kompensavimo_uz_i/8/40359513/10145955

**Comment by goriolus** [comment]
http://www.vilnius.lt/lit/Del_vilniaus_darzelio_mokyklos_malunelis/8/41367970/15460147

**Comment by goriolus** [comment]
DĖL VILNIAUS DARŽELIO-MOKYKLOS „MALŪNĖLIS" STEIGIMO IR NUOSTATŲ TVIRTINIMO
http://www.vilnius.lt/lit/Del_vilniaus_darzelio_mokyklos_malunelis/8/41367970/15460147
